<?php
declare(strict_types=1);
namespace App\Services;
use App\Models\NotificationModel;
use Throwable;

class SubcontractNotificationService
{
 private $db;private NotificationModel $model;
 private array $cfg=['work-orders'=>['SUBCONTRACT_WORK_ORDER','subcontract_work_orders','work_order_no','work_orders.approve','/subcontract-work-orders/'],'measurements'=>['SUBCONTRACT_MEASUREMENT','subcontract_measurements','measurement_no','measurements.approve','/subcontract-measurements/'],'ra-bills'=>['SUBCONTRACT_RA_BILL','subcontract_ra_bills','ra_bill_no','ra_bills.certify','/subcontract-ra-bills/'],'payments'=>['SUBCONTRACT_PAYMENT','subcontract_payments','payment_no','payments.approve','/subcontract-payments/']];
 public function __construct(){$this->db=db_connect();$this->model=new NotificationModel();}
 public function notify(string$type,array$r,string$action,int$actor):void{$c=$this->cfg[$type]??null;if(!$c)return;$event=$this->db->table('notification_event_masters')->where(['event_code'=>$c[0].'_'.$action,'is_active'=>1])->get()->getRowArray();if(!$event){log_message('error','Subcontract notification event missing: {event}',['event'=>$c[0].'_'.$action]);return;}$project=$this->db->table('projects')->select('id,project_name,branch_id')->where(['id'=>$r['project_id'],'company_id'=>$r['company_id']])->get()->getRowArray();if(!$project)return;$approval=in_array($action,['SUBMIT','SUBMITTED','VERIFY','VERIFIED','APPROVE','APPROVED'],true)&&in_array($action,['SUBMIT','SUBMITTED','VERIFY','VERIFIED'],true);$users=$approval?$this->approvers($r,$project,$c[3],$actor):$this->originator($r);$verb=strtolower(str_replace('_',' ',$action));$title=ucwords(str_replace('_',' ',strtolower($c[0]))).' '.$verb;$message=(string)$r[$c[2]].' has been '.$verb.'.';foreach($users as$u){$id=$this->model->insert(['company_id'=>$r['company_id'],'recipient_user_id'=>$u['id'],'event_id'=>$event['id'],'project_id'=>$r['project_id'],'source_module'=>$c[0],'source_table'=>$c[1],'source_record_id'=>$r['id'],'title'=>$title,'message'=>$message,'action_url'=>$c[4].$r['id'],'is_read'=>0,'email_sent'=>0,'created_by'=>$actor],true);if(is_int($id)&&$id>0)$this->email($id,$u,$title,$message,$project);}}
 private function approvers(array$r,array$p,string$permission,int$actor):array{$today=date('Y-m-d');$b=$this->db->table('users u')->distinct()->select('u.id,u.email,u.first_name,u.last_name')->join('user_statuses us','us.id=u.user_status_id')->join('user_roles ur','ur.user_id=u.id AND ur.company_id=u.company_id','left')->join('roles ro','ro.id=ur.role_id AND ro.company_id=ur.company_id','left')->join('role_permissions rp','rp.role_id=ro.id AND rp.company_id=ro.company_id','left')->join('permissions pe','pe.id=rp.permission_id','left')->join('user_branch_access uba','uba.user_id=u.id AND uba.company_id=u.company_id','left')->join('user_branch_access_access_level_masters al','al.id=uba.access_level_id','left')->where('u.company_id',$r['company_id'])->where('u.id !=',$actor)->where(['u.is_active'=>1,'u.active'=>1,'us.status_code'=>'ACTIVE','us.is_login_allowed'=>1])->where('u.deleted_at',null)->groupStart()->where('u.is_super_admin',1)->orGroupStart()->where(['ur.is_active'=>1,'ro.is_active'=>1,'rp.is_active'=>1,'pe.is_active'=>1,'pe.permission_code'=>$permission])->where('ur.deleted_at',null)->where('ro.deleted_at',null)->where('rp.deleted_at',null)->where('pe.deleted_at',null)->groupEnd()->groupEnd();if((int)$p['branch_id']>0)$b->groupStart()->where('u.is_super_admin',1)->orGroupStart()->where(['uba.branch_id'=>$p['branch_id'],'uba.is_active'=>1,'al.is_active'=>1])->whereIn('al.access_level_code',['OPERATE','MANAGE'])->where('uba.deleted_at',null)->groupEnd()->groupEnd();return$b->get()->getResultArray();}
 private function originator(array$r):array{$id=(int)($r['submitted_by']??$r['created_by']??0);return$id?$this->db->table('users')->select('id,email,first_name,last_name')->where(['id'=>$id,'company_id'=>$r['company_id'],'is_active'=>1,'active'=>1])->where('deleted_at',null)->get()->getResultArray():[];}
 private function email(int$id,array$u,string$s,string$m,array$p):void{if(trim((string)($u['email']??''))===''){$this->model->update($id,['email_error'=>'Recipient email address is empty.']);return;}try{$e=service('email');$e->setTo($u['email'])->setSubject($s)->setMessage('<p>Hello '.esc(trim(($u['first_name']??'').' '.($u['last_name']??''))).',</p><p>'.esc($m).'</p><p>Project: '.esc($p['project_name']).'</p>');if(!$e->send())throw new \RuntimeException(strip_tags($e->printDebugger(['headers'])));$this->model->update($id,['email_sent'=>1,'email_sent_at'=>date('Y-m-d H:i:s'),'email_error'=>null]);}catch(Throwable$x){$this->model->update($id,['email_error'=>mb_substr($x->getMessage(),0,1000)]);}}
}
