<?php
declare(strict_types=1);
namespace App\Controllers\Api;

use App\Controllers\BaseController;
use CodeIgniter\HTTP\ResponseInterface;
use Throwable;

class DashboardReportsController extends BaseController
{
    private function user(): ?object { return auth('session')->user(); }
    private function out(string $message, string $key, mixed $value, int $status = 200): ResponseInterface
    { return $this->response->setStatusCode($status)->setJSON(['success'=>true,'message'=>$message,'data'=>[$key=>$value]]); }
    private function fail(string $message, int $status = 422): ResponseInterface
    { return $this->response->setStatusCode($status)->setJSON(['success'=>false,'message'=>$message]); }
    private function input(): array { $v=$this->request->getJSON(true); return is_array($v)?$v:[]; }
    private function master(string $table, string $codeColumn, string $code): ?int
    { $r=db_connect()->table($table)->select('id')->where([$codeColumn=>$code,'is_active'=>1])->get()->getRowArray(); return $r?(int)$r['id']:null; }
    private function safe(callable $fn): ResponseInterface
    { try { return $fn(); } catch(Throwable $e) { log_message('error','Module 11 API error: {error}',['error'=>$e->getMessage()]); return $this->fail('Unable to complete dashboard or report operation.',500); } }
    private function projectFilter($builder, string $alias='x'): void
    { if($this->request->getGet('project_id')!==null)$builder->where($alias.'.project_id',(int)$this->request->getGet('project_id')); }
    private function scalar(string $sql,array $binds): float
    { $r=db_connect()->query($sql,$binds)->getRowArray(); return (float)($r['total']??0); }

    public function masters(): ResponseInterface
    { return $this->safe(function(){ if(!$u=$this->user())return $this->fail('Authentication required.',401); $db=db_connect(); $tables=['alert_types'=>['dashboard_alerts_alert_type_masters','alert_type_name'],'alert_severities'=>['dashboard_alerts_severity_masters','severity_name'],'alert_statuses'=>['dashboard_alerts_status_masters','status_name'],'alert_actions'=>['dashboard_alert_actions_action_type_masters','action_type_name'],'review_types'=>['management_review_notes_review_type_masters','review_type_name'],'review_priorities'=>['management_review_notes_priority_masters','priority_name'],'review_statuses'=>['management_review_notes_status_masters','status_name']]; $data=[]; foreach($tables as$k=>$v)$data[$k]=$db->table($v[0])->where('is_active',1)->orderBy('sort_order')->get()->getResultArray(); return $this->out('Dashboard and report masters retrieved.','masters',$data); }); }

    public function overview(): ResponseInterface
    { return $this->safe(function(){ if(!$u=$this->user())return $this->fail('Authentication required.',401); $c=(int)$u->company_id;$db=db_connect();$project=(int)($this->request->getGet('project_id')??0);$pw=$project?' AND project_id=?':'';$bind=$project?[$c,$project]:[$c];
        $projects=(int)$this->scalar("SELECT COUNT(*) total FROM projects WHERE company_id=? AND deleted_at IS NULL".($project?' AND id=?':''),$bind);
        $openAlerts=(int)$this->scalar("SELECT COUNT(*) total FROM dashboard_alerts a JOIN dashboard_alerts_status_masters s ON s.id=a.status_id WHERE a.company_id=? AND s.status_code IN ('OPEN','ACKNOWLEDGED','IN_PROGRESS')".($project?' AND a.project_id=?':''),$bind);
        $reports=(int)$this->scalar("SELECT COUNT(*) total FROM daily_site_reports WHERE company_id=? AND deleted_at IS NULL".$pw,$bind);
        $issues=(int)$this->scalar("SELECT COUNT(*) total FROM daily_site_issues i JOIN daily_site_issues_status_masters s ON s.id=i.status_id WHERE i.company_id=? AND i.deleted_at IS NULL AND s.status_code NOT IN ('RESOLVED','CLOSED')".($project?' AND EXISTS(SELECT 1 FROM daily_site_reports r WHERE r.id=i.daily_report_id AND r.project_id=?)':''),$bind);
        $budget=$this->scalar("SELECT COALESCE(SUM(total_budget),0) total FROM project_budgets b JOIN project_budgets_status_masters s ON s.id=b.status_id WHERE b.company_id=? AND b.deleted_at IS NULL AND s.status_code='APPROVED'".($project?' AND b.project_id=?':''),$bind);
        $expense=$this->scalar("SELECT COALESCE(SUM(net_payable),0) total FROM expense_bills b JOIN expense_bills_status_masters s ON s.id=b.status_id WHERE b.company_id=? AND b.deleted_at IS NULL AND s.status_code='POSTED'".($project?' AND b.project_id=?':''),$bind);
        $sub=$this->scalar("SELECT COALESCE(SUM(net_certified_amount),0) total FROM subcontract_ra_bills b JOIN subcontract_ra_bills_status_masters s ON s.id=b.status_id WHERE b.company_id=? AND b.deleted_at IS NULL AND s.status_code='CERTIFIED'".($project?' AND b.project_id=?':''),$bind);
        $labour=$this->scalar("SELECT COALESCE(SUM(net_payable),0) total FROM labour_wage_periods w JOIN labour_wage_periods_status_masters s ON s.id=w.status_id WHERE w.company_id=? AND s.status_code='APPROVED'".($project?' AND w.project_id=?':''),$bind);
        return $this->out('Management dashboard generated.','dashboard',['project_count'=>$projects,'daily_report_count'=>$reports,'open_issue_count'=>$issues,'open_alert_count'=>$openAlerts,'approved_budget'=>$budget,'expense_actual'=>$expense,'subcontract_actual'=>$sub,'labour_actual'=>$labour,'total_actual_cost'=>$expense+$sub+$labour,'budget_balance'=>$budget-($expense+$sub+$labour)]); }); }

    public function projectPerformance(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$b=db_connect()->table('projects p')->select("p.id,p.project_code,p.project_name,p.planned_start_date,p.expected_completion_date,COALESCE(MAX(d.report_date),NULL) latest_report_date,COALESCE(MAX(d.planned_progress_percentage),0) planned_progress_percentage,COALESCE(MAX(d.actual_progress_percentage),0) actual_progress_percentage,COUNT(DISTINCT d.id) report_count")->join('daily_site_reports d','d.project_id=p.id AND d.deleted_at IS NULL','left')->where('p.company_id',(int)$u->company_id)->where('p.deleted_at',null);if($this->request->getGet('project_id')!==null)$b->where('p.id',(int)$this->request->getGet('project_id'));$rows=$b->groupBy('p.id')->orderBy('p.project_name')->get()->getResultArray();foreach($rows as&$r)$r['progress_variance']=(float)$r['actual_progress_percentage']-(float)$r['planned_progress_percentage'];return$this->out('Project performance report generated.','projects',$rows);}); }

    public function dailyProgress(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$b=db_connect()->table('daily_site_reports d')->select('d.id,d.project_id,p.project_name,d.site_id,s.site_name,d.report_no,d.report_date,d.total_manpower,d.total_equipment,d.planned_progress_percentage,d.actual_progress_percentage,d.safety_incident_count,st.status_code,st.status_name')->join('projects p','p.id=d.project_id')->join('project_sites s','s.id=d.site_id')->join('daily_site_reports_status_masters st','st.id=d.status_id')->where('d.company_id',(int)$u->company_id)->where('d.deleted_at',null);$this->projectFilter($b,'d');if($f=$this->request->getGet('from_date'))$b->where('d.report_date >=',$f);if($t=$this->request->getGet('to_date'))$b->where('d.report_date <=',$t);return$this->out('Daily progress report generated.','daily_progress',$b->orderBy('d.report_date','DESC')->limit(500)->get()->getResultArray());}); }

    public function costReport(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$b=db_connect()->table('project_cost_snapshots s')->select('s.*,p.project_code,p.project_name,l.snapshot_level_code')->join('projects p','p.id=s.project_id')->join('project_cost_snapshots_snapshot_level_masters l','l.id=s.snapshot_level_id')->where('s.company_id',(int)$u->company_id);$this->projectFilter($b,'s');return$this->out('Project cost report generated.','cost_report',$b->orderBy('s.snapshot_date','DESC')->orderBy('s.id','DESC')->limit(500)->get()->getResultArray());}); }

    public function labourReport(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$b=db_connect()->table('labour_attendance_entries e')->select('b.project_id,p.project_name,b.attendance_date,COUNT(e.id) worker_entries,SUM(e.regular_hours) regular_hours,SUM(e.overtime_hours) overtime_hours')->join('labour_attendance_batches b','b.id=e.batch_id')->join('projects p','p.id=b.project_id')->where('e.company_id',(int)$u->company_id);$this->projectFilter($b,'b');if($f=$this->request->getGet('from_date'))$b->where('b.attendance_date >=',$f);if($t=$this->request->getGet('to_date'))$b->where('b.attendance_date <=',$t);return$this->out('Labour utilisation report generated.','labour_report',$b->groupBy('b.project_id,b.attendance_date')->orderBy('b.attendance_date','DESC')->limit(500)->get()->getResultArray());}); }

    public function materialReport(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$b=db_connect()->table('daily_material_consumption c')->select('c.project_id,p.project_name,c.material_id,m.material_code,m.material_name,SUM(c.issued_qty) issued_qty,SUM(c.consumed_qty) consumed_qty,SUM(c.returned_qty) returned_qty,SUM(c.wasted_qty) wasted_qty,SUM(c.consumption_value) consumption_value')->join('projects p','p.id=c.project_id')->join('materials m','m.id=c.material_id')->where('c.company_id',(int)$u->company_id)->where('c.deleted_at',null);$this->projectFilter($b,'c');return$this->out('Material consumption report generated.','material_report',$b->groupBy('c.project_id,c.material_id')->orderBy('p.project_name')->get()->getResultArray());}); }

    public function subcontractReport(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$b=db_connect()->table('subcontract_work_orders w')->select('w.id,w.project_id,p.project_name,w.work_order_no,w.total_order_value,w.revised_order_value,w.certified_amount,w.paid_amount,s.status_code,s.status_name')->join('projects p','p.id=w.project_id')->join('subcontract_work_orders_status_masters s','s.id=w.status_id')->where('w.company_id',(int)$u->company_id)->where('w.deleted_at',null);$this->projectFilter($b,'w');return$this->out('Subcontract commitment report generated.','subcontract_report',$b->orderBy('w.id','DESC')->get()->getResultArray());}); }

    public function expenseReport(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$b=db_connect()->table('expense_bills b')->select('b.id,b.project_id,p.project_name,b.internal_voucher_no,b.bill_date,b.net_payable,b.paid_amount,b.outstanding_amount,s.status_code,s.status_name')->join('projects p','p.id=b.project_id')->join('expense_bills_status_masters s','s.id=b.status_id')->where('b.company_id',(int)$u->company_id)->where('b.deleted_at',null);$this->projectFilter($b,'b');if($f=$this->request->getGet('from_date'))$b->where('b.bill_date >=',$f);if($t=$this->request->getGet('to_date'))$b->where('b.bill_date <=',$t);return$this->out('Expense report generated.','expense_report',$b->orderBy('b.bill_date','DESC')->limit(500)->get()->getResultArray());}); }

    public function alerts(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$b=db_connect()->table('dashboard_alerts a')->select('a.*,p.project_name,t.alert_type_code,t.alert_type_name,v.severity_code,v.severity_name,s.status_code,s.status_name')->join('projects p','p.id=a.project_id','left')->join('dashboard_alerts_alert_type_masters t','t.id=a.alert_type_id')->join('dashboard_alerts_severity_masters v','v.id=a.severity_id')->join('dashboard_alerts_status_masters s','s.id=a.status_id')->where('a.company_id',(int)$u->company_id);$this->projectFilter($b,'a');if($status=$this->request->getGet('status'))$b->where('s.status_code',strtoupper($status));return$this->out('Dashboard alerts retrieved.','alerts',$b->orderBy('a.id','DESC')->limit(500)->get()->getResultArray());}); }

    public function createAlert(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$d=$this->input();foreach(['alert_type_id','severity_id','title','message']as$f)if(empty($d[$f]))return$this->fail($f.' is required.');$db=db_connect();$status=$this->master('dashboard_alerts_status_masters','status_code','OPEN');$row=['company_id'=>(int)$u->company_id,'project_id'=>isset($d['project_id'])?(int)$d['project_id']:null,'site_id'=>isset($d['site_id'])?(int)$d['site_id']:null,'alert_no'=>'ALT-'.date('YmdHis').'-'.random_int(100,999),'alert_type_id'=>(int)$d['alert_type_id'],'severity_id'=>(int)$d['severity_id'],'title'=>trim((string)$d['title']),'message'=>trim((string)$d['message']),'source_module'=>$d['source_module']??'MANUAL','source_table'=>$d['source_table']??null,'source_record_id'=>$d['source_record_id']??null,'alert_date'=>date('Y-m-d H:i:s'),'due_date'=>$d['due_date']??null,'assigned_to'=>$d['assigned_to']??null,'status_id'=>$status,'created_by'=>(int)$u->id];$db->table('dashboard_alerts')->insert($row);$id=(int)$db->insertID();$this->alertAction($id,'CREATED',null,'OPEN','Manual alert created.',(int)$u->company_id,(int)$u->id);return$this->out('Dashboard alert created.','alert',$db->table('dashboard_alerts')->where('id',$id)->get()->getRowArray(),201);}); }

    public function alertAction(int $id,string $code,?string $old=null,?string $new=null,?string $notes=null,?int $company=null,?int $actor=null): ?ResponseInterface
    { $internal=$company!==null; $fn=function()use($id,$code,$old,$new,$notes,$company,$actor,$internal){$u=$this->user();if(!$internal&&!$u)return$this->fail('Authentication required.',401);$c=$company??(int)$u->company_id;$a=$actor??(int)$u->id;$db=db_connect();$row=$db->table('dashboard_alerts a')->select('a.*,s.status_code')->join('dashboard_alerts_status_masters s','s.id=a.status_id')->where(['a.id'=>$id,'a.company_id'=>$c])->get()->getRowArray();if(!$row)return$this->fail('Alert not found.',404);$d=$internal?[]:$this->input();$action=strtoupper($internal?$code:(string)($d['action']??$code));$map=['ACKNOWLEDGE'=>'ACKNOWLEDGED','START'=>'IN_PROGRESS','RESOLVE'=>'RESOLVED','DISMISS'=>'DISMISSED'];$newCode=$new??($map[$action]??null);if(!$newCode)return$this->fail('Unsupported alert action.');$status=$this->master('dashboard_alerts_status_masters','status_code',$newCode);if(!$status)return$this->fail('Alert status master is missing.',500);$update=['status_id'=>$status,'updated_at'=>date('Y-m-d H:i:s')];if($newCode==='ACKNOWLEDGED'){$update['acknowledged_by']=$a;$update['acknowledged_at']=date('Y-m-d H:i:s');}if($newCode==='RESOLVED'){$update['resolved_by']=$a;$update['resolved_at']=date('Y-m-d H:i:s');$update['resolution']=$d['resolution']??$notes;}$db->table('dashboard_alerts')->where('id',$id)->update($update);$actionMaster=$this->master('dashboard_alert_actions_action_type_masters','action_type_code',$newCode==='RESOLVED'?'RESOLVED':($newCode==='DISMISSED'?'DISMISSED':($newCode==='ACKNOWLEDGED'?'ACKNOWLEDGED':'STATUS_CHANGED')));$db->table('dashboard_alert_actions')->insert(['company_id'=>$c,'alert_id'=>$id,'action_type_id'=>$actionMaster,'old_status'=>$old??$row['status_code'],'new_status'=>$newCode,'action_notes'=>$d['notes']??$notes,'action_by'=>$a,'action_at'=>date('Y-m-d H:i:s')]);if($internal)return null;return$this->out('Dashboard alert updated.','alert',$db->table('dashboard_alerts')->where('id',$id)->get()->getRowArray());};if($internal){$fn();return null;}return$this->safe($fn); }

    public function reviews(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$b=db_connect()->table('management_review_notes r')->select('r.*,p.project_name,t.review_type_code,t.review_type_name,v.priority_code,v.priority_name,s.status_code,s.status_name')->join('projects p','p.id=r.project_id')->join('management_review_notes_review_type_masters t','t.id=r.review_type_id')->join('management_review_notes_priority_masters v','v.id=r.priority_id')->join('management_review_notes_status_masters s','s.id=r.status_id')->where('r.company_id',(int)$u->company_id)->where('r.deleted_at',null);$this->projectFilter($b,'r');return$this->out('Management reviews retrieved.','management_reviews',$b->orderBy('r.review_date','DESC')->limit(500)->get()->getResultArray());}); }

    public function createReview(): ResponseInterface
    { return $this->safe(function(){if(!$u=$this->user())return$this->fail('Authentication required.',401);$d=$this->input();foreach(['project_id','review_date','review_type_id','subject','observations','priority_id']as$f)if(empty($d[$f]))return$this->fail($f.' is required.');$db=db_connect();$row=['company_id'=>(int)$u->company_id,'project_id'=>(int)$d['project_id'],'site_id'=>$d['site_id']??null,'review_date'=>$d['review_date'],'review_type_id'=>(int)$d['review_type_id'],'subject'=>$d['subject'],'observations'=>$d['observations'],'decisions'=>$d['decisions']??null,'action_required'=>$d['action_required']??null,'assigned_to'=>$d['assigned_to']??null,'target_date'=>$d['target_date']??null,'priority_id'=>(int)$d['priority_id'],'status_id'=>$this->master('management_review_notes_status_masters','status_code','OPEN'),'created_by'=>(int)$u->id,'updated_by'=>(int)$u->id];$db->table('management_review_notes')->insert($row);$id=(int)$db->insertID();return$this->out('Management review created.','management_review',$db->table('management_review_notes')->where('id',$id)->get()->getRowArray(),201);}); }

    public function reviewAction(int $id,string $action): ResponseInterface
    { return $this->safe(function()use($id,$action){if(!$u=$this->user())return$this->fail('Authentication required.',401);$map=['start'=>'IN_PROGRESS','complete'=>'COMPLETED','cancel'=>'CANCELLED'];$code=$map[strtolower($action)]??null;if(!$code)return$this->fail('Unsupported review action.');$db=db_connect();$row=$db->table('management_review_notes')->where(['id'=>$id,'company_id'=>(int)$u->company_id])->where('deleted_at',null)->get()->getRowArray();if(!$row)return$this->fail('Management review not found.',404);$up=['status_id'=>$this->master('management_review_notes_status_masters','status_code',$code),'updated_by'=>(int)$u->id];if($code==='COMPLETED'){$up['completed_at']=date('Y-m-d H:i:s');$up['completed_by']=(int)$u->id;}$db->table('management_review_notes')->where('id',$id)->update($up);return$this->out('Management review updated.','management_review',$db->table('management_review_notes')->where('id',$id)->get()->getRowArray());}); }
}
