<?php
declare(strict_types=1);
namespace App\Controllers\Api;

class ExpenseRequestsController extends ExpenseApiController
{
    public function index(){return$this->safe(function(){if(!$u=$this->user())return$this->missing();$c=$this->company($u);$b=db_connect()->table('expense_requests r')->select('r.*,s.status_code,s.status_name,p.project_name,ps.site_name,z.zone_name')->join('expense_requests_status_masters s','s.id=r.status_id')->join('projects p','p.id=r.project_id')->join('project_sites ps','ps.id=r.site_id','left')->join('site_work_zones z','z.id=r.zone_id','left')->where('r.company_id',$c)->where('r.deleted_at',null);foreach(['project_id','site_id','zone_id','status_id']as$f)if($this->request->getGet($f)!==null)$b->where('r.'.$f,(int)$this->request->getGet($f));return$this->ok('Expense requests retrieved.','expense_requests',$b->orderBy('r.id','DESC')->get()->getResultArray());});}
    public function show(int$id){return$this->safe(function()use($id){if(!$u=$this->user())return$this->missing();$c=$this->company($u);if(!$r=$this->row('expense_requests',$id,$c))return$this->missing('Expense request not found.');$r['items']=db_connect()->table('expense_request_items i')->select('i.*,ec.category_code,ec.category_name')->join('expense_categories ec','ec.id=i.expense_category_id')->where(['i.request_id'=>$id,'i.company_id'=>$c])->where('i.deleted_at',null)->get()->getResultArray();$r['approvals']=$this->approvalRows('REQUEST',$id,$c);return$this->ok('Expense request retrieved.','expense_request',$r);});}
    public function create(){return$this->save();} public function update(int$id){return$this->save($id);}
    private function save(?int$id=null){return$this->safe(function()use($id){if(!$u=$this->user())return$this->missing();$d=$this->input();$e=$this->required($d,['project_id','request_no','request_date','purpose']);if($e)return$this->invalid($e);$c=$this->company($u);$project=(int)$d['project_id'];if(!$this->project($project,$u,true))return$this->invalid(['project_id'=>'Project is invalid or inaccessible.']);$site=isset($d['site_id'])?(int)$d['site_id']:null;$zone=isset($d['zone_id'])?(int)$d['zone_id']:null;if(!$this->validSite($site,$project,$c)||!$this->validZone($zone,$site,$c))return$this->invalid(['site_id'=>'Site or zone does not belong to the project.']);$db=db_connect();$existing=$id?$this->row('expense_requests',$id,$c):null;if($id&&!$existing)return$this->missing('Expense request not found.');if($existing&&$this->statusCode('expense_requests_status_masters','status_code',(int)$existing['status_id'])!=='DRAFT')return$this->conflict('Only draft expense requests can be updated.');$dup=$db->table('expense_requests')->where(['company_id'=>$c,'request_no'=>trim($d['request_no'])])->where('deleted_at',null);if($id)$dup->where('id !=',$id);if($dup->countAllResults())return$this->conflict('Expense request number already exists.');$row=['company_id'=>$c,'project_id'=>$project,'site_id'=>$site,'zone_id'=>$zone,'request_no'=>trim($d['request_no']),'request_date'=>$d['request_date'],'required_date'=>$d['required_date']??null,'purpose'=>trim($d['purpose']),'requested_by'=>(int)($d['requested_by']??$u->id),'updated_by'=>(int)$u->id];if($id)$db->table('expense_requests')->where('id',$id)->update($row);else{$row['status_id']=$this->masterId('expense_requests_status_masters','status_code','DRAFT');$row['estimated_amount']=0;$row['created_by']=(int)$u->id;$db->table('expense_requests')->insert($row);$id=(int)$db->insertID();}return$this->ok('Expense request saved.','expense_request',$this->row('expense_requests',$id,$c),$existing?200:201);});}
    public function addItem(int$id){return$this->safe(function()use($id){if(!$u=$this->user())return$this->missing();$c=$this->company($u);if(!$r=$this->row('expense_requests',$id,$c))return$this->missing('Expense request not found.');if($this->statusCode('expense_requests_status_masters','status_code',(int)$r['status_id'])!=='DRAFT')return$this->conflict('Items can be added only to a draft request.');$d=$this->input();$e=$this->required($d,['expense_category_id','description','quantity','estimated_rate']);if($e)return$this->invalid($e);$q=(float)$d['quantity'];$rate=(float)$d['estimated_rate'];$amount=round($q*$rate,2);$row=['company_id'=>$c,'project_id'=>$r['project_id'],'request_id'=>$id,'expense_category_id'=>(int)$d['expense_category_id'],'budget_line_id'=>isset($d['budget_line_id'])?(int)$d['budget_line_id']:null,'description'=>trim($d['description']),'quantity'=>$q,'estimated_rate'=>$rate,'estimated_amount'=>$amount,'approved_amount'=>0,'notes'=>$d['notes']??null,'created_by'=>(int)$u->id,'updated_by'=>(int)$u->id];$db=db_connect();$db->table('expense_request_items')->insert($row);$itemId=(int)$db->insertID();$this->recalculate($id);return$this->ok('Expense request item added.','expense_request_item',$this->row('expense_request_items',$itemId,$c),201);});}
    public function action(int$id,string$action){return$this->safe(function()use($id,$action){if(!$u=$this->user())return$this->missing();$c=$this->company($u);if(!$r=$this->row('expense_requests',$id,$c))return$this->missing('Expense request not found.');$old=$this->statusCode('expense_requests_status_masters','status_code',(int)$r['status_id']);$map=['submit'=>['DRAFT','SUBMITTED','SUBMITTED'],'approve'=>['SUBMITTED','APPROVED','APPROVED'],'reject'=>['SUBMITTED','REJECTED','REJECTED'],'cancel'=>['DRAFT','CANCELLED','CANCELLED']];if(!isset($map[$action])||$old!==$map[$action][0])return$this->conflict('Invalid expense request workflow transition.');if($action==='submit'&&db_connect()->table('expense_request_items')->where(['request_id'=>$id,'company_id'=>$c])->where('deleted_at',null)->countAllResults()===0)return$this->conflict('Add at least one request item before submission.');[$from,$to,$approval]=$map[$action];$d=$this->input();$row=['status_id'=>$this->masterId('expense_requests_status_masters','status_code',$to),'updated_by'=>(int)$u->id];if($action==='submit'){$row['submitted_by']=(int)$u->id;$row['submitted_at']=$this->now();}if(in_array($action,['approve','reject'],true)){$row['approved_by']=$action==='approve'?(int)$u->id:null;$row['approved_at']=$action==='approve'?$this->now():null;$row['approval_remarks']=$d['remarks']??null;if($action==='approve')db_connect()->table('expense_request_items')->where(['request_id'=>$id,'company_id'=>$c])->where('deleted_at',null)->set('approved_amount','estimated_amount',false)->update();}db_connect()->table('expense_requests')->where('id',$id)->update($row);$this->logStatus('REQUEST',$id,$from,$to,$c,(int)$u->id,$d['remarks']??null);$this->approval('REQUEST',$id,$approval,$c,(int)$u->id,$d['remarks']??null);$updated=$this->row('expense_requests',$id,$c);$this->notifier->notify('REQUEST',$updated,strtoupper($action==='submit'?'SUBMITTED':$action),(int)$u->id);return$this->ok('Expense request '.$action.' completed.','expense_request',$updated);});}
    private function recalculate(int$id):void{$sum=(float)(db_connect()->table('expense_request_items')->selectSum('estimated_amount','total')->where('request_id',$id)->where('deleted_at',null)->get()->getRowArray()['total']??0);db_connect()->table('expense_requests')->where('id',$id)->update(['estimated_amount'=>$sum]);}
    private function approvalRows(string$type,int$id,int$c):array{$et=$this->masterId('expense_approvals_entity_type_masters','entity_type_code',$type);return db_connect()->table('expense_approvals a')->select('a.*,m.action_type_code,m.action_type_name')->join('expense_approvals_action_type_masters m','m.id=a.action_type_id')->where(['a.company_id'=>$c,'a.entity_type_id'=>$et,'a.entity_id'=>$id])->get()->getResultArray();}
}
