<?php
declare(strict_types=1);
namespace App\Controllers\Api;

class ExpensePaymentsController extends ExpenseApiController
{
    public function index(){return$this->safe(function(){if(!$u=$this->user())return$this->missing();$b=db_connect()->table('expense_payments p')->select('p.*,s.status_code,s.status_name,b.internal_voucher_no,b.payee_name')->join('expense_payments_status_masters s','s.id=p.status_id')->join('expense_bills b','b.id=p.bill_id')->where('p.company_id',$this->company($u))->where('p.deleted_at',null);foreach(['project_id','bill_id','status_id']as$f)if($this->request->getGet($f)!==null)$b->where('p.'.$f,(int)$this->request->getGet($f));return$this->ok('Expense payments retrieved.','expense_payments',$b->orderBy('p.id','DESC')->get()->getResultArray());});}
    public function show(int$id){return$this->safe(function()use($id){if(!$u=$this->user())return$this->missing();if(!$r=$this->row('expense_payments',$id,$this->company($u)))return$this->missing('Expense payment not found.');return$this->ok('Expense payment retrieved.','expense_payment',$r);});}
    public function create(){return$this->save();}public function update(int$id){return$this->save($id);}
    private function save(?int$id=null){return$this->safe(function()use($id){if(!$u=$this->user())return$this->missing();$d=$this->input();$e=$this->required($d,['bill_id','payment_no','payment_date','payment_mode_id','amount']);if($e)return$this->invalid($e);$c=$this->company($u);if(!$bill=$this->row('expense_bills',(int)$d['bill_id'],$c))return$this->invalid(['bill_id'=>'Expense bill not found.']);if($this->statusCode('expense_bills_status_masters','status_code',(int)$bill['status_id'])!=='POSTED')return$this->conflict('Only posted expense bills can be paid.');$existing=$id?$this->row('expense_payments',$id,$c):null;if($id&&!$existing)return$this->missing('Expense payment not found.');if($existing&&$this->statusCode('expense_payments_status_masters','status_code',(int)$existing['status_id'])!=='DRAFT')return$this->conflict('Only draft payments can be updated.');$amount=(float)$d['amount'];if($amount<=0||$amount>(float)$bill['outstanding_amount']+0.01)return$this->invalid(['amount'=>'Payment must be positive and cannot exceed bill outstanding.']);$row=['company_id'=>$c,'project_id'=>$bill['project_id'],'bill_id'=>$bill['id'],'petty_cash_account_id'=>isset($d['petty_cash_account_id'])?(int)$d['petty_cash_account_id']:null,'payment_no'=>trim($d['payment_no']),'payment_date'=>$d['payment_date'],'payment_mode_id'=>(int)$d['payment_mode_id'],'reference_no'=>$d['reference_no']??null,'amount'=>$amount,'tds_deducted'=>(float)($d['tds_deducted']??0),'remarks'=>$d['remarks']??null,'updated_by'=>(int)$u->id];$db=db_connect();$dup=$db->table('expense_payments')->where(['company_id'=>$c,'payment_no'=>$row['payment_no']])->where('deleted_at',null);if($id)$dup->where('id !=',$id);if($dup->countAllResults())return$this->conflict('Payment number already exists.');if($id)$db->table('expense_payments')->where('id',$id)->update($row);else{$row['status_id']=$this->masterId('expense_payments_status_masters','status_code','DRAFT');$row['created_by']=(int)$u->id;$db->table('expense_payments')->insert($row);$id=(int)$db->insertID();}return$this->ok('Expense payment saved.','expense_payment',$this->row('expense_payments',$id,$c),$existing?200:201);});}
    public function action(int$id,string$action){return$this->safe(function()use($id,$action){if(!$u=$this->user())return$this->missing();$c=$this->company($u);if(!$p=$this->row('expense_payments',$id,$c))return$this->missing('Expense payment not found.');$old=$this->statusCode('expense_payments_status_masters','status_code',(int)$p['status_id']);$map=['submit'=>['DRAFT','SUBMITTED','SUBMITTED'],'approve'=>['SUBMITTED','APPROVED','APPROVED'],'reject'=>['SUBMITTED','REJECTED','REJECTED'],'mark-paid'=>['APPROVED','PAID','APPROVED'],'cancel'=>['DRAFT','CANCELLED','CANCELLED']];if(!isset($map[$action])||$old!==$map[$action][0])return$this->conflict('Invalid expense payment workflow transition.');[$from,$to,$approval]=$map[$action];$d=$this->input();$row=['status_id'=>$this->masterId('expense_payments_status_masters','status_code',$to),'updated_by'=>(int)$u->id];if($action==='submit')$row['submitted_by']=(int)$u->id;if($action==='approve')$row['approved_by']=(int)$u->id;if($action==='mark-paid'){$row['paid_by']=(int)$u->id;$row['paid_at']=$this->now();}$db=db_connect();$db->transStart();$db->table('expense_payments')->where('id',$id)->update($row);if($action==='mark-paid')$this->updateBillPayment((int)$p['bill_id'],$c);$this->logStatus('PAYMENT',$id,$from,$to,$c,(int)$u->id,$d['remarks']??null);$this->approval('PAYMENT',$id,$approval,$c,(int)$u->id,$d['remarks']??null);$db->transComplete();$updated=$this->row('expense_payments',$id,$c);$this->notifier->notify('PAYMENT',$updated,strtoupper(str_replace('-','_',$action==='submit'?'SUBMITTED':$action)),(int)$u->id);return$this->ok('Expense payment '.$action.' completed.','expense_payment',$updated);});}
    private function updateBillPayment(int$billId,int$c):void{$db=db_connect();$paid=(float)($db->table('expense_payments p')->selectSum('p.amount','total')->join('expense_payments_status_masters s','s.id=p.status_id')->where(['p.bill_id'=>$billId,'p.company_id'=>$c,'s.status_code'=>'PAID'])->where('p.deleted_at',null)->get()->getRowArray()['total']??0);$bill=$this->row('expense_bills',$billId,$c);$out=max(0,(float)$bill['net_payable']-$paid);$code=$out<=0.01?'PAID':($paid>0?'PARTIALLY_PAID':'UNPAID');$db->table('expense_bills')->where('id',$billId)->update(['paid_amount'=>$paid,'outstanding_amount'=>$out,'payment_status_id'=>$this->masterId('expense_bills_payment_status_masters','payment_status_code',$code)]);}
}
