<?php
declare(strict_types=1);
namespace App\Controllers\Api;
use App\Models\LabourAttendanceExceptionModel;
use CodeIgniter\HTTP\ResponseInterface;
class LabourAttendanceExceptionsController extends LabourApiController
{
 private LabourAttendanceExceptionModel $model; public function __construct(){parent::__construct();$this->model=new LabourAttendanceExceptionModel();}
 public function index():ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$b=$this->base()->where('e.company_id',$this->companyId($u));foreach(['project_id','site_id','worker_id','status_id']as$f){$v=(int)($this->request->getGet($f)??0);if($v)$b->where('e.'.$f,$v);}return$this->ok('Attendance exceptions retrieved.','exceptions',$b->orderBy('e.incident_date','DESC')->get()->getResultArray());}
 public function show(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->row($id,$u);return$r?$this->ok('Attendance exception retrieved.','exception',$r):$this->notFound('Attendance exception not found.');}
 public function create():ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$in=$this->normalizeWorker($this->input()??[],$u);$e=$this->validateInput($in,$u);if($e)return$this->invalid($e);$d=$this->data($in)+['company_id'=>$this->companyId($u),'status_id'=>1,'created_by'=>(int)$u->id,'updated_by'=>(int)$u->id];if(!$this->model->insert($d))return$this->invalid($this->model->errors());return$this->ok('Attendance exception created.','exception',$this->row((int)$this->model->getInsertID(),$u),201);}
 public function update(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$old=$this->row($id,$u);if(!$old)return$this->notFound('Attendance exception not found.');if(!in_array($old['status_code'],['DRAFT','REJECTED'],true))return$this->response->setStatusCode(409)->setJSON(['success'=>false,'message'=>'Only Draft or Rejected exceptions can be edited.']);$in=$this->normalizeWorker($this->input()??[],$u);$merged=array_merge($old,$in);$e=$this->validateInput($merged,$u);if($e)return$this->invalid($e);$d=$this->data($in);$d['updated_by']=(int)$u->id;$this->model->update($id,$d);return$this->show($id);}
 public function delete(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->row($id,$u);if(!$r)return$this->notFound();if($r['status_code']!=='DRAFT')return$this->response->setStatusCode(409)->setJSON(['success'=>false,'message'=>'Only Draft exceptions can be archived.']);$this->model->delete($id);return$this->ok('Attendance exception archived.','id',$id);}
 public function submit(int$id):ResponseInterface{return$this->transition($id,'DRAFT','SUBMITTED');} public function approve(int$id):ResponseInterface{return$this->transition($id,'SUBMITTED','APPROVED');} public function reject(int$id):ResponseInterface{return$this->transition($id,'SUBMITTED','REJECTED');}
 private function transition(int$id,string$from,string$to):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->row($id,$u);if(!$r)return$this->notFound();if($r['status_code']!==$from)return$this->response->setStatusCode(409)->setJSON(['success'=>false,'message'=>'Invalid attendance-exception status transition.']);$sid=$this->masterId('labour_attendance_exception_status_masters','status_code',$to);$input=$this->input()??[];$d=['status_id'=>$sid,'updated_by'=>(int)$u->id];if($to==='SUBMITTED')$d+=['submitted_by'=>(int)$u->id,'submitted_at'=>$this->now()];if(in_array($to,['APPROVED','REJECTED'],true))$d+=['approved_by'=>(int)$u->id,'approved_at'=>$this->now(),'approval_remarks'=>($input['remarks']??null)];$this->model->update($id,$d);return$this->show($id);}
 private function validateInput(array$in,object$u):array{$e=$this->required($in,['project_id','worker_id','incident_date','exception_category_id']);if(!$this->project((int)($in['project_id']??0),$u,true))$e['project_id']='Select an accessible project.';if(!empty($in['site_id'])&&!$this->site((int)$in['site_id'],(int)$in['project_id'],$u,true))$e['site_id']='Select a valid project site.';if(!$this->record('labour_workers',(int)($in['worker_id']??0),$this->companyId($u),true))$e['worker_id']='Select a valid worker.';if(!$this->activeMaster('labour_attendance_exception_category_masters',(int)($in['exception_category_id']??0)))$e['exception_category_id']='Select a valid exception category.';return$e;}
 private function data(array$in):array{return array_intersect_key($in,array_flip(['project_id','site_id','worker_id','incident_date','exception_category_id','regular_hours_credit','adjusted_check_in','adjusted_check_out','overtime_hours_credit','reason']));}
 private function normalizeWorker(array$in,object$u):array{$aliases=['parent_project_id'=>'project_id','site_location_id'=>'site_id','category_id'=>'exception_category_id','regular_hours_to_credit'=>'regular_hours_credit','overtime_hours_to_credit'=>'overtime_hours_credit','adjusted_checkin'=>'adjusted_check_in','adjusted_checkout'=>'adjusted_check_out'];foreach($aliases as$from=>$to)if(isset($in[$from])&&!isset($in[$to]))$in[$to]=$in[$from];if(empty($in['worker_id'])&&!empty($in['worker_code'])){$r=db_connect()->table('labour_workers')->select('id')->where(['company_id'=>$this->companyId($u),'worker_code'=>$in['worker_code']])->where('deleted_at',null)->get()->getRowArray();if($r)$in['worker_id']=(int)$r['id'];}return$in;}
 private function row(int$id,object$u):?array{return$this->base()->where('e.company_id',$this->companyId($u))->where('e.id',$id)->get()->getRowArray();}
 private function base(){return db_connect()->table('labour_attendance_exceptions e')->select('e.*,p.project_code,p.project_name,s.site_name,w.worker_code,w.worker_name,c.category_code,c.category_name,st.status_code,st.status_name')->join('projects p','p.id=e.project_id')->join('project_sites s','s.id=e.site_id','left')->join('labour_workers w','w.id=e.worker_id')->join('labour_attendance_exception_category_masters c','c.id=e.exception_category_id')->join('labour_attendance_exception_status_masters st','st.id=e.status_id')->where('e.deleted_at',null);}
}
