<?php
declare(strict_types=1);
namespace App\Controllers\Api;
use CodeIgniter\HTTP\ResponseInterface;
use Throwable;

class LabourWorkersController extends LabourApiController
{
    public function index(): ResponseInterface
    {
        $u=$this->user();if(!$u)return $this->unauthorized();$b=db_connect()->table('labour_workers w')->select('w.*,c.category_code,c.category_name,lc.contractor_code,lc.contractor_name,lc.subcontractor_id,sc.contractor_code AS subcontractor_code,sc.contractor_name AS subcontractor_name,s.status_code,s.status_name')->join('labour_categories c','c.id=w.labour_category_id')->join('labour_contractors lc','lc.id=w.contractor_id AND lc.company_id=w.company_id','left')->join('subcontractors sc','sc.id=lc.subcontractor_id AND sc.company_id=lc.company_id','left')->join('labour_workers_status_masters s','s.id=w.status_id')->where('w.company_id',$this->companyId($u))->where('w.deleted_at',null);
        foreach(['labour_category_id','contractor_id','status_id']as$f)if(ctype_digit((string)($this->request->getGet($f)??'')))$b->where('w.'.$f,(int)$this->request->getGet($f));if(ctype_digit((string)($this->request->getGet('subcontractor_id')??'')))$b->where('lc.subcontractor_id',(int)$this->request->getGet('subcontractor_id'));$q=trim((string)($this->request->getGet('search')??''));if($q!=='')$b->groupStart()->like('w.worker_code',$q)->orLike('w.worker_name',$q)->orLike('w.phone',$q)->orLike('sc.contractor_name',$q)->groupEnd();return $this->ok('Labour workers retrieved successfully.','labour_workers',$b->orderBy('w.id','DESC')->get()->getResultArray());
    }
    public function show(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=db_connect()->table('labour_workers w')->select('w.*,lc.contractor_code,lc.contractor_name,lc.subcontractor_id,sc.contractor_code AS subcontractor_code,sc.contractor_name AS subcontractor_name')->join('labour_contractors lc','lc.id=w.contractor_id AND lc.company_id=w.company_id','left')->join('subcontractors sc','sc.id=lc.subcontractor_id AND sc.company_id=lc.company_id','left')->where('w.id',$id)->where('w.company_id',$this->companyId($u))->where('w.deleted_at',null)->get()->getRowArray();if(!$r)return$this->notFound();$r['documents']=db_connect()->table('labour_worker_documents')->where('worker_id',$id)->where('deleted_at',null)->get()->getResultArray();return$this->ok('Labour worker retrieved successfully.','labour_worker',$r);}
    public function create():ResponseInterface{return$this->save(null);} public function update(int$id):ResponseInterface{return$this->save($id);}
    public function delete(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->record('labour_workers',$id,$this->companyId($u),true);if(!$r)return$this->notFound();foreach([['labour_project_assignments','worker_id'],['labour_attendance_entries','worker_id'],['labour_wage_lines','worker_id'],['labour_payments','worker_id']]as[$t,$f])if(db_connect()->table($t)->where($f,$id)->countAllResults())return$this->response->setStatusCode(409)->setJSON(['success'=>false,'message'=>'Worker is in use and cannot be deleted.']);db_connect()->table('labour_workers')->where('id',$id)->update(['deleted_at'=>$this->now(),'updated_by'=>(int)$u->id]);return$this->response->setJSON(['success'=>true,'message'=>'Labour worker deleted successfully.']);}

    public function documents(int$workerId):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();if(!$this->record('labour_workers',$workerId,$this->companyId($u),true))return$this->notFound();return$this->ok('Worker documents retrieved successfully.','worker_documents',db_connect()->table('labour_worker_documents')->where('company_id',$this->companyId($u))->where('worker_id',$workerId)->where('deleted_at',null)->orderBy('id','DESC')->get()->getResultArray());}
    public function createDocument(int$workerId):ResponseInterface{return$this->saveDocument($workerId,null);}public function updateDocument(int$workerId,int$id):ResponseInterface{return$this->saveDocument($workerId,$id);}
    public function verifyDocument(int$workerId,int$id):ResponseInterface
    { $u=$this->user();if(!$u)return$this->unauthorized();$d=$this->record('labour_worker_documents',$id,$this->companyId($u),true);if(!$d||(int)$d['worker_id']!==$workerId)return$this->notFound();$in=$this->input();$status=(int)($in['verification_status_id']??0);if(!$this->activeMaster('labour_worker_documents_verification_status_masters',$status))return$this->invalid(['verification_status_id'=>'Select a valid active verification status.']);db_connect()->table('labour_worker_documents')->where('id',$id)->update(['verification_status_id'=>$status,'verified_by'=>(int)$u->id,'verified_at'=>$this->now(),'remarks'=>$in['remarks']??$d['remarks'],'updated_at'=>$this->now()]);return$this->ok('Worker document verification updated successfully.','worker_document',$this->record('labour_worker_documents',$id,$this->companyId($u),true)); }
    public function deleteDocument(int$workerId,int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$d=$this->record('labour_worker_documents',$id,$this->companyId($u),true);if(!$d||(int)$d['worker_id']!==$workerId)return$this->notFound();db_connect()->table('labour_worker_documents')->where('id',$id)->update(['deleted_at'=>$this->now()]);return$this->response->setJSON(['success'=>true,'message'=>'Worker document deleted successfully.']);}

    private function save(?int$id):ResponseInterface
    { $u=$this->user();if(!$u)return$this->unauthorized();$in=$this->input();if($in===null)return$this->invalid(['body'=>'A valid JSON request body is required.']);$company=$this->companyId($u);$old=$id?$this->record('labour_workers',$id,$company,true):null;if($id&&!$old)return$this->notFound();$fields=['labour_category_id','contractor_id','worker_code','worker_name','employment_source_id','gender_id','date_of_birth','phone','emergency_contact_name','emergency_contact_phone','blood_group','address','native_place','id_type_id','id_number_masked','date_joined','date_left','wage_basis_id','base_wage_rate','overtime_rate_per_hour','bank_name','bank_account_name','bank_account_no_masked','bank_ifsc','safety_induction_date','status_id','notes'];$data=array_intersect_key($in,array_flip($fields));$m=array_merge($old??[],$data);$e=$this->required($m,['labour_category_id','worker_code','worker_name','employment_source_id','gender_id','id_type_id','date_joined','wage_basis_id','status_id']);foreach(['labour_category_id'=>['labour_categories',true],'employment_source_id'=>['labour_workers_employment_source_masters',false],'gender_id'=>['labour_workers_gender_masters',false],'id_type_id'=>['labour_workers_id_type_masters',false],'wage_basis_id'=>['labour_workers_wage_basis_masters',false],'status_id'=>['labour_workers_status_masters',false]]as$f=>[$t,$sc]){if($sc){if(!$this->record($t,(int)($m[$f]??0),$company,true))$e[$f]='Select a valid company labour category.';}elseif(!$this->activeMaster($t,(int)($m[$f]??0)))$e[$f]='Select a valid active master value.';}if(!empty($m['contractor_id'])&&!$this->record('labour_contractors',(int)$m['contractor_id'],$company,true))$e['contractor_id']='Select a valid company contractor.';$dup=db_connect()->table('labour_workers')->where('company_id',$company)->where('worker_code',$m['worker_code']??'')->where('deleted_at',null);if($id)$dup->where('id !=',$id);if($dup->countAllResults())$e['worker_code']='Worker code already exists.';if($e)return$this->invalid($e);$data['updated_by']=(int)$u->id;$data['updated_at']=$this->now();if(!$id){$data+=['company_id'=>$company,'created_by'=>(int)$u->id,'created_at'=>$this->now()];}try{$b=db_connect()->table('labour_workers');$id?$b->where('id',$id)->update($data):$b->insert($data);$id??=(int)db_connect()->insertID();return$this->ok($old?'Labour worker updated successfully.':'Labour worker created successfully.','labour_worker',$this->record('labour_workers',$id,$company,true),$old?200:201);}catch(Throwable$x){return$this->serverError('Labour worker save failed.',$x);} }

    private function saveDocument(int$workerId,?int$id):ResponseInterface
    { $u=$this->user();if(!$u)return$this->unauthorized();$company=$this->companyId($u);if(!$this->record('labour_workers',$workerId,$company,true))return$this->notFound();$old=$id?$this->record('labour_worker_documents',$id,$company,true):null;if($id&&(!$old||(int)$old['worker_id']!==$workerId))return$this->notFound();$in=$this->input();if($in===null)return$this->invalid(['body'=>'A valid JSON request body is required.']);$fields=['document_type_id','document_name','document_number','issue_date','expiry_date','file_path','verification_status_id','remarks'];$data=array_intersect_key($in,array_flip($fields));$m=array_merge($old??[],$data);$e=$this->required($m,['document_name','file_path','verification_status_id']);if(!$this->activeMaster('labour_worker_documents_verification_status_masters',(int)($m['verification_status_id']??0)))$e['verification_status_id']='Select a valid verification status.';if($e)return$this->invalid($e);$data['updated_at']=$this->now();if(!$id)$data+=['company_id'=>$company,'worker_id'=>$workerId,'created_by'=>(int)$u->id,'created_at'=>$this->now()];$b=db_connect()->table('labour_worker_documents');$id?$b->where('id',$id)->update($data):$b->insert($data);$id??=(int)db_connect()->insertID();return$this->ok($old?'Worker document updated successfully.':'Worker document created successfully.','worker_document',$this->record('labour_worker_documents',$id,$company,true),$old?200:201); }
}
