<?php
declare(strict_types=1);
namespace App\Controllers\Api;
use CodeIgniter\HTTP\ResponseInterface;

class LabourPaymentsController extends LabourApiController
{
 public function index():ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$b=db_connect()->table('labour_payments p')->select('p.*,s.status_code,s.status_name,m.payment_mode_code,m.payment_mode_name,w.worker_name,c.contractor_name')->join('labour_payments_status_masters s','s.id=p.status_id')->join('labour_payments_payment_mode_masters m','m.id=p.payment_mode_id')->join('labour_workers w','w.id=p.worker_id','left')->join('labour_contractors c','c.id=p.contractor_id','left')->where('p.company_id',$this->companyId($u));foreach(['wage_period_id','worker_id','contractor_id','status_id']as$f)if(ctype_digit((string)($this->request->getGet($f)??'')))$b->where('p.'.$f,(int)$this->request->getGet($f));return$this->ok('Labour payments retrieved successfully.','labour_payments',$b->orderBy('p.id','DESC')->get()->getResultArray());}
 public function show(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->record('labour_payments',$id,$this->companyId($u));return$r?$this->ok('Labour payment retrieved successfully.','labour_payment',$r):$this->notFound();}
 public function create():ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$in=$this->input();if(!$in)return$this->invalid(['body'=>'A valid JSON request body is required.']);$c=$this->companyId($u);$e=$this->required($in,['wage_period_id','payment_no','payment_date','payment_mode_id','amount','recipient_name']);$period=$this->record('labour_wage_periods',(int)($in['wage_period_id']??0),$c);if(!$period||!in_array($this->periodStatus((int)$period['status_id']),['APPROVED','PARTIALLY_PAID'],true))$e['wage_period_id']='Select an approved wage period.';if(!$this->activeMaster('labour_payments_payment_mode_masters',(int)($in['payment_mode_id']??0)))$e['payment_mode_id']='Select a valid payment mode.';if((float)($in['amount']??0)<=0)$e['amount']='Payment amount must be greater than zero.';if(empty($in['worker_id'])&&empty($in['contractor_id']))$e['recipient']='Select either a worker or contractor.';if(!empty($in['worker_id'])&&!$this->record('labour_workers',(int)$in['worker_id'],$c,true))$e['worker_id']='Select a valid worker.';if(!empty($in['contractor_id'])&&!$this->record('labour_contractors',(int)$in['contractor_id'],$c,true))$e['contractor_id']='Select a valid contractor.';if(db_connect()->table('labour_payments')->where('company_id',$c)->where('payment_no',$in['payment_no']??'')->countAllResults())$e['payment_no']='Payment number already exists.';if($e)return$this->invalid($e);$draft=$this->masterId('labour_payments_status_masters','status_code','DRAFT');$d=array_intersect_key($in,array_flip(['wage_period_id','wage_line_id','worker_id','contractor_id','payment_no','payment_date','payment_mode_id','reference_no','amount','recipient_name','receipt_path','remarks']));$d+=['company_id'=>$c,'status_id'=>$draft,'created_by'=>(int)$u->id,'updated_by'=>(int)$u->id,'created_at'=>$this->now(),'updated_at'=>$this->now()];db_connect()->table('labour_payments')->insert($d);$id=(int)db_connect()->insertID();return$this->ok('Labour payment created successfully.','labour_payment',$this->record('labour_payments',$id,$c),201);}
 public function submit(int$id):ResponseInterface{return$this->transition($id,'DRAFT','SUBMITTED');}public function approve(int$id):ResponseInterface{return$this->transition($id,'SUBMITTED','APPROVED');}public function markPaid(int$id):ResponseInterface{return$this->transition($id,'APPROVED','PAID');}public function cancel(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->record('labour_payments',$id,$this->companyId($u));if(!$r)return$this->notFound();$old=$this->paymentStatus((int)$r['status_id']);if($old==='PAID')return$this->response->setStatusCode(409)->setJSON(['success'=>false,'message'=>'A paid payment cannot be cancelled.']);return$this->transition($id,$old,'CANCELLED');}
 private function transition(int$id,string$from,string$to):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$c=$this->companyId($u);$r=$this->record('labour_payments',$id,$c);if(!$r)return$this->notFound();$old=$this->paymentStatus((int)$r['status_id']);if($old!==$from)return$this->response->setStatusCode(409)->setJSON(['success'=>false,'message'=>'Invalid payment status transition.']);$sid=$this->masterId('labour_payments_status_masters','status_code',$to);$d=['status_id'=>$sid,'updated_by'=>(int)$u->id,'updated_at'=>$this->now()];if($to==='APPROVED')$d+=['approved_by'=>(int)$u->id,'approved_at'=>$this->now()];if($to==='PAID')$d+=['paid_by'=>(int)$u->id,'paid_at'=>$this->now()];db_connect()->table('labour_payments')->where('id',$id)->update($d);if($to==='PAID')$this->refreshPaymentState((int)$r['wage_period_id'],isset($r['wage_line_id'])?(int)$r['wage_line_id']:null);$this->statusLog($c,'PAYMENT',$id,$old,$to,$to,null,(int)$u->id);return$this->ok('Labour payment '.strtolower($to).' successfully.','labour_payment',$this->record('labour_payments',$id,$c));}
 private function refreshPaymentState(int$periodId,?int$lineId):void{$paid=$this->masterId('labour_payments_status_masters','status_code','PAID');if($lineId){$line=$this->record('labour_wage_lines',$lineId,(int)$this->record('labour_wage_periods',$periodId,(int)$this->user()->company_id)['company_id']);$sum=(float)(db_connect()->table('labour_payments')->selectSum('amount')->where('wage_line_id',$lineId)->where('status_id',$paid)->get()->getRowArray()['amount']??0);$code=$sum>=(float)$line['net_amount']?'PAID':'PARTIALLY_PAID';$sid=$this->masterId('labour_wage_lines_payment_status_masters','payment_status_code',$code);db_connect()->table('labour_wage_lines')->where('id',$lineId)->update(['payment_status_id'=>$sid]);}$period=db_connect()->table('labour_wage_periods')->where('id',$periodId)->get()->getRowArray();$sum=(float)(db_connect()->table('labour_payments')->selectSum('amount')->where('wage_period_id',$periodId)->where('status_id',$paid)->get()->getRowArray()['amount']??0);$code=$sum>=(float)$period['net_payable']?'PAID':'PARTIALLY_PAID';$sid=$this->masterId('labour_wage_periods_status_masters','status_code',$code);db_connect()->table('labour_wage_periods')->where('id',$periodId)->update(['status_id'=>$sid]);}
 private function paymentStatus(int$id):string{return(string)(db_connect()->table('labour_payments_status_masters')->select('status_code')->where('id',$id)->get()->getRowArray()['status_code']??'UNKNOWN');}private function periodStatus(int$id):string{return(string)(db_connect()->table('labour_wage_periods_status_masters')->select('status_code')->where('id',$id)->get()->getRowArray()['status_code']??'UNKNOWN');}
}
