<?php
declare(strict_types=1);
namespace App\Controllers\Api;
use CodeIgniter\HTTP\ResponseInterface;

class LabourAssignmentsController extends LabourApiController
{
 public function index():ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$b=db_connect()->table('labour_project_assignments a')->select('a.*,w.worker_code,w.worker_name,lc.id AS contractor_id,lc.contractor_code,lc.contractor_name,lc.subcontractor_id,sc.contractor_code AS subcontractor_code,sc.contractor_name AS subcontractor_name,c.category_name,p.project_code,p.project_name,s.site_code,s.site_name,z.zone_code,z.zone_name,st.status_code,st.status_name')->join('labour_workers w','w.id=a.worker_id')->join('labour_contractors lc','lc.id=w.contractor_id AND lc.company_id=w.company_id','left')->join('subcontractors sc','sc.id=lc.subcontractor_id AND sc.company_id=lc.company_id','left')->join('labour_categories c','c.id=a.labour_category_id')->join('projects p','p.id=a.project_id')->join('project_sites s','s.id=a.site_id')->join('site_work_zones z','z.id=a.zone_id','left')->join('labour_project_assignments_status_masters st','st.id=a.status_id')->where('a.company_id',$this->companyId($u))->where('a.deleted_at',null);foreach(['project_id','site_id','zone_id','worker_id','status_id']as$f)if(ctype_digit((string)($this->request->getGet($f)??'')))$b->where('a.'.$f,(int)$this->request->getGet($f));if(ctype_digit((string)($this->request->getGet('subcontractor_id')??'')))$b->where('lc.subcontractor_id',(int)$this->request->getGet('subcontractor_id'));return$this->ok('Labour assignments retrieved successfully.','labour_assignments',$b->orderBy('a.id','DESC')->get()->getResultArray());}
 public function show(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=db_connect()->table('labour_project_assignments a')->select('a.*,w.worker_code,w.worker_name,lc.id AS contractor_id,lc.contractor_code,lc.contractor_name,lc.subcontractor_id,sc.contractor_code AS subcontractor_code,sc.contractor_name AS subcontractor_name')->join('labour_workers w','w.id=a.worker_id')->join('labour_contractors lc','lc.id=w.contractor_id AND lc.company_id=w.company_id','left')->join('subcontractors sc','sc.id=lc.subcontractor_id AND sc.company_id=lc.company_id','left')->where('a.id',$id)->where('a.company_id',$this->companyId($u))->where('a.deleted_at',null)->get()->getRowArray();return$r?$this->ok('Labour assignment retrieved successfully.','labour_assignment',$r):$this->notFound();}
 public function create():ResponseInterface{return$this->save(null);}public function update(int$id):ResponseInterface{return$this->save($id);}
 public function delete(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->record('labour_project_assignments',$id,$this->companyId($u),true);if(!$r)return$this->notFound();if(db_connect()->table('labour_attendance_entries')->where('assignment_id',$id)->countAllResults()||db_connect()->table('labour_wage_lines')->where('assignment_id',$id)->countAllResults())return$this->response->setStatusCode(409)->setJSON(['success'=>false,'message'=>'Assignment is in use and cannot be deleted.']);db_connect()->table('labour_project_assignments')->where('id',$id)->update(['deleted_at'=>$this->now(),'updated_by'=>(int)$u->id]);return$this->response->setJSON(['success'=>true,'message'=>'Labour assignment deleted successfully.']);}
 private function save(?int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$in=$this->input();if($in===null)return$this->invalid(['body'=>'A valid JSON request body is required.']);$c=$this->companyId($u);$old=$id?$this->record('labour_project_assignments',$id,$c,true):null;if($id&&!$old)return$this->notFound();$fields=['project_id','site_id','zone_id','worker_id','labour_category_id','assigned_from','assigned_until','wage_basis_id','agreed_wage_rate','overtime_rate','shift_name','status_id','remarks'];$d=array_intersect_key($in,array_flip($fields));$m=array_merge($old??[],$d);$e=$this->required($m,['project_id','site_id','worker_id','labour_category_id','assigned_from','wage_basis_id','status_id']);if(!$this->site((int)($m['site_id']??0),(int)($m['project_id']??0),$u,true))$e['site_id']='Select an accessible site belonging to the project.';if(!$this->record('labour_workers',(int)($m['worker_id']??0),$c,true))$e['worker_id']='Select a valid company worker.';if(!$this->record('labour_categories',(int)($m['labour_category_id']??0),$c,true))$e['labour_category_id']='Select a valid company category.';if(!$this->activeMaster('labour_project_assignments_wage_basis_masters',(int)($m['wage_basis_id']??0)))$e['wage_basis_id']='Select a valid wage basis.';if(!$this->activeMaster('labour_project_assignments_status_masters',(int)($m['status_id']??0)))$e['status_id']='Select a valid assignment status.';if(!empty($m['zone_id'])&&db_connect()->table('site_work_zones')->where('id',(int)$m['zone_id'])->where('site_id',(int)$m['site_id'])->where('deleted_at',null)->countAllResults()===0)$e['zone_id']='Select a zone belonging to the site.';if(!empty($m['assigned_until'])&&$m['assigned_until']<$m['assigned_from'])$e['assigned_until']='Assigned-until date cannot precede assigned-from date.';if($e)return$this->invalid($e);$d['updated_by']=(int)$u->id;$d['updated_at']=$this->now();if(!$id)$d+=['company_id'=>$c,'created_by'=>(int)$u->id,'created_at'=>$this->now()];$b=db_connect()->table('labour_project_assignments');$id?$b->where('id',$id)->update($d):$b->insert($d);$id??=(int)db_connect()->insertID();return$this->ok($old?'Labour assignment updated successfully.':'Labour assignment created successfully.','labour_assignment',$this->record('labour_project_assignments',$id,$c,true),$old?200:201);}
}
