<?php
declare(strict_types=1);
namespace App\Controllers\Api;
use CodeIgniter\HTTP\ResponseInterface;

class MaterialMastersController extends MaterialApiController
{
    public function masters():ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$db=db_connect();$tables=['storage_types'=>'material_categories_storage_type_masters','supplier_statuses'=>'material_suppliers_status_masters','request_priorities'=>'material_requests_priority_masters','request_statuses'=>'material_requests_status_masters','request_item_statuses'=>'material_request_items_item_status_masters','po_statuses'=>'material_purchase_orders_status_masters','po_item_statuses'=>'material_purchase_order_items_item_status_masters','receipt_statuses'=>'material_receipts_status_masters','quality_statuses'=>'material_receipt_items_quality_status_masters','transaction_types'=>'material_transactions_transaction_type_masters','transaction_statuses'=>'material_transactions_status_masters'];$out=[];foreach($tables as$k=>$t)$out[$k]=$db->table($t)->where('is_active',1)->orderBy('sort_order','ASC')->get()->getResultArray();$companyId=$this->company($u);$out['units']=$db->table('units_of_measurement')->where('company_id',$companyId)->where('is_active',1)->where('deleted_at',null)->orderBy('unit_name')->get()->getResultArray();$out['brands']=$db->table('material_brands')->select('id,brand_code,brand_name,description')->where('company_id',$companyId)->where('is_active',1)->where('deleted_at',null)->orderBy('brand_name','ASC')->get()->getResultArray();return$this->ok('Material masters retrieved successfully.','masters',$out);}
    public function categories():ResponseInterface{return$this->listing('material_categories','material_categories',['category_code','category_name']);}
    public function category(int$id):ResponseInterface{return$this->one('material_categories',$id,'material_category');}
    public function createCategory():ResponseInterface{return$this->saveCategory(null);}public function updateCategory(int$id):ResponseInterface{return$this->saveCategory($id);}
    public function deleteCategory(int$id):ResponseInterface{return$this->remove('material_categories',$id,[['material_categories','parent_id'],['materials','material_category_id']],'Material category');}
    public function brands():ResponseInterface{return$this->listing('material_brands','material_brands',['brand_code','brand_name','description']);}
    public function brand(int$id):ResponseInterface{return$this->one('material_brands',$id,'material_brand');}
    public function createBrand():ResponseInterface{return$this->saveBrand(null);}public function updateBrand(int$id):ResponseInterface{return$this->saveBrand($id);}
    public function deleteBrand(int$id):ResponseInterface{return$this->remove('material_brands',$id,[['materials','brand_id']],'Material brand');}
    public function materials():ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$b=db_connect()->table('materials m')->select('m.*,mc.category_code,mc.category_name,uom.unit_code,uom.unit_name,mb.brand_code,mb.brand_name,mb.description AS brand_description')->join('material_categories mc','mc.id=m.material_category_id AND mc.company_id=m.company_id','left')->join('units_of_measurement uom','uom.id=m.base_uom_id AND uom.company_id=m.company_id','left')->join('material_brands mb','mb.id=m.brand_id AND mb.company_id=m.company_id AND mb.deleted_at IS NULL','left')->where('m.company_id',$this->company($u))->where('m.deleted_at',null);$q=trim((string)($this->request->getGet('search')??''));if($q!==''){$b->groupStart()->like('m.material_code',$q)->orLike('m.material_name',$q)->orLike('m.specification',$q)->orLike('mb.brand_name',$q)->groupEnd();}if(($a=$this->request->getGet('is_active'))!==null)$b->where('m.is_active',(int)$a);return$this->ok('Materials retrieved successfully.','materials',$b->orderBy('m.id','DESC')->get()->getResultArray());}
    public function material(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->materialRow($id,$this->company($u));return$r?$this->ok('Material retrieved successfully.','material',$r):$this->notFound();}
    public function createMaterial():ResponseInterface{return$this->saveMaterial(null);}public function updateMaterial(int$id):ResponseInterface{return$this->saveMaterial($id);}
    public function deleteMaterial(int$id):ResponseInterface{return$this->remove('materials',$id,[['material_request_items','material_id'],['material_purchase_order_items','material_id'],['material_receipt_items','material_id'],['material_transaction_items','material_id']],'Material');}
    public function suppliers():ResponseInterface{return$this->listing('material_suppliers','material_suppliers',['supplier_code','supplier_name','contact_person','phone','gstin']);}
    public function supplier(int$id):ResponseInterface{return$this->one('material_suppliers',$id,'material_supplier');}
    public function createSupplier():ResponseInterface{return$this->saveSupplier(null);}public function updateSupplier(int$id):ResponseInterface{return$this->saveSupplier($id);}
    public function deleteSupplier(int$id):ResponseInterface{return$this->remove('material_suppliers',$id,[['material_purchase_orders','supplier_id'],['material_receipts','supplier_id']],'Material supplier');}
    private function listing(string$t,string$k,array$search):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$b=db_connect()->table($t)->where('company_id',$this->company($u))->where('deleted_at',null);$q=trim((string)($this->request->getGet('search')??''));if($q!==''){$b->groupStart();foreach($search as$i=>$f)$i?$b->orLike($f,$q):$b->like($f,$q);$b->groupEnd();}if(($a=$this->request->getGet('is_active'))!==null)$b->where('is_active',(int)$a);return$this->ok(ucwords(str_replace('_',' ',$k)).' retrieved successfully.',$k,$b->orderBy('id','DESC')->get()->getResultArray());}
    private function one(string$t,int$id,string$k):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->row($t,$id,$this->company($u));return$r?$this->ok(ucwords(str_replace('_',' ',$k)).' retrieved successfully.',$k,$r):$this->notFound();}
    private function saveCategory(?int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$in=$this->input();if($in===null)return$this->invalid(['body'=>'A valid JSON request body is required.']);$c=$this->company($u);$old=$id?$this->row('material_categories',$id,$c):null;if($id&&!$old)return$this->notFound();$f=['parent_id','category_code','category_name','storage_type_id','quality_check_required','description','display_order','is_active'];$d=array_intersect_key($in,array_flip($f));$m=array_merge($old??[],$d);$e=$this->required($m,['category_code','category_name','storage_type_id']);if(!$this->active('material_categories_storage_type_masters',(int)($m['storage_type_id']??0)))$e['storage_type_id']='Select a valid storage type.';if(!empty($m['parent_id'])&&((int)$m['parent_id']===$id||!$this->row('material_categories',(int)$m['parent_id'],$c)))$e['parent_id']='Select a valid parent category.';$b=db_connect()->table('material_categories')->where(['company_id'=>$c,'category_code'=>$m['category_code']??''])->where('deleted_at',null);if($id)$b->where('id !=',$id);if($b->countAllResults())$e['category_code']='Category code already exists.';if($e)return$this->invalid($e);return$this->persist('material_categories',$d,$id,'material_category','Material category',$u);}
    private function saveBrand(?int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$in=$this->input();if($in===null)return$this->invalid(['body'=>'A valid JSON request body is required.']);$c=$this->company($u);$old=$id?$this->row('material_brands',$id,$c):null;if($id&&!$old)return$this->notFound();$f=['brand_code','brand_name','description','is_active'];$d=array_intersect_key($in,array_flip($f));if(array_key_exists('brand_code',$d))$d['brand_code']=strtoupper(trim((string)$d['brand_code']));if(array_key_exists('brand_name',$d))$d['brand_name']=trim((string)$d['brand_name']);if(array_key_exists('description',$d))$d['description']=trim((string)$d['description'])?:null;$m=array_merge($old??[],$d);$e=$this->required($m,['brand_code','brand_name']);foreach(['brand_code'=>'Brand code','brand_name'=>'Brand name']as$field=>$label){$b=db_connect()->table('material_brands')->where('company_id',$c)->where($field,$m[$field]??'')->where('deleted_at',null);if($id)$b->where('id !=',$id);if($b->countAllResults())$e[$field]=$label.' already exists.';}if($e)return$this->invalid($e);return$this->persist('material_brands',$d,$id,'material_brand','Material brand',$u);}
    private function saveMaterial(?int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$in=$this->input();if($in===null)return$this->invalid(['body'=>'A valid JSON request body is required.']);$c=$this->company($u);$old=$id?$this->row('materials',$id,$c):null;if($id&&!$old)return$this->notFound();$f=['material_category_id','base_uom_id','brand_id','material_code','material_name','specification','hsn_code','gst_rate','standard_rate','minimum_stock_qty','reorder_qty','storage_location_hint','quality_check_required','batch_tracking_required','is_active','notes'];$d=array_intersect_key($in,array_flip($f));if(array_key_exists('brand_id',$d)&&($d['brand_id']===''||$d['brand_id']===0||$d['brand_id']==='0'))$d['brand_id']=null;$m=array_merge($old??[],$d);$e=$this->required($m,['material_category_id','base_uom_id','material_code','material_name']);if(!$this->row('material_categories',(int)($m['material_category_id']??0),$c))$e['material_category_id']='Select a valid company material category.';if(!$this->row('units_of_measurement',(int)($m['base_uom_id']??0),$c))$e['base_uom_id']='Select a valid company UOM.';if(!empty($m['brand_id'])){$brand=$this->row('material_brands',(int)$m['brand_id'],$c);if(!$brand||(int)$brand['is_active']!==1)$e['brand_id']='Select a valid active company material brand.';}foreach(['gst_rate','standard_rate','minimum_stock_qty','reorder_qty']as$f2)if((float)($m[$f2]??0)<0)$e[$f2]='Value cannot be negative.';$b=db_connect()->table('materials')->where(['company_id'=>$c,'material_code'=>$m['material_code']??''])->where('deleted_at',null);if($id)$b->where('id !=',$id);if($b->countAllResults())$e['material_code']='Material code already exists.';if($e)return$this->invalid($e);return$this->persist('materials',$d,$id,'material','Material',$u);}
    private function saveSupplier(?int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$in=$this->input();if($in===null)return$this->invalid(['body'=>'A valid JSON request body is required.']);$c=$this->company($u);$old=$id?$this->row('material_suppliers',$id,$c):null;if($id&&!$old)return$this->notFound();$f=['supplier_code','supplier_name','contact_person','phone','alternate_phone','email','gstin','pan','address_line1','address_line2','city','state_name','postal_code','payment_terms_days','credit_limit','bank_name','bank_account_name','bank_account_no','bank_ifsc','rating','status_id','notes'];$d=array_intersect_key($in,array_flip($f));$m=array_merge($old??[],$d);$e=$this->required($m,['supplier_code','supplier_name','status_id']);if(!$this->active('material_suppliers_status_masters',(int)($m['status_id']??0)))$e['status_id']='Select a valid supplier status.';$b=db_connect()->table('material_suppliers')->where(['company_id'=>$c,'supplier_code'=>$m['supplier_code']??''])->where('deleted_at',null);if($id)$b->where('id !=',$id);if($b->countAllResults())$e['supplier_code']='Supplier code already exists.';if($e)return$this->invalid($e);return$this->persist('material_suppliers',$d,$id,'material_supplier','Material supplier',$u);}
    private function persist(string$t,array$d,?int$id,string$k,string$l,object$u):ResponseInterface{$old=$id!==null;$d['updated_by']=(int)$u->id;$d['updated_at']=$this->now();if(!$id)$d+=['company_id'=>$this->company($u),'created_by'=>(int)$u->id,'created_at'=>$this->now()];$b=db_connect()->table($t);$id?$b->where('id',$id)->update($d):$b->insert($d);$id??=(int)db_connect()->insertID();$companyId=$this->company($u);$record=$t==='materials'?$this->materialRow($id,$companyId):$this->row($t,$id,$companyId);return$this->ok($l.($old?' updated':' created').' successfully.',$k,$record,$old?200:201);}
    private function materialRow(int$id,int$companyId):?array{return db_connect()->table('materials m')->select('m.*,mc.category_code,mc.category_name,uom.unit_code,uom.unit_name,mb.brand_code,mb.brand_name,mb.description AS brand_description')->join('material_categories mc','mc.id=m.material_category_id AND mc.company_id=m.company_id','left')->join('units_of_measurement uom','uom.id=m.base_uom_id AND uom.company_id=m.company_id','left')->join('material_brands mb','mb.id=m.brand_id AND mb.company_id=m.company_id AND mb.deleted_at IS NULL','left')->where('m.id',$id)->where('m.company_id',$companyId)->where('m.deleted_at',null)->get()->getRowArray();}
    private function remove(string$t,int$id,array$refs,string$l):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();if(!$this->row($t,$id,$this->company($u)))return$this->notFound();foreach($refs as[$rt,$rf])if(db_connect()->table($rt)->where($rf,$id)->where('deleted_at',null)->countAllResults())return$this->conflict($l.' is in use and cannot be deleted.');db_connect()->table($t)->where('id',$id)->update(['deleted_at'=>$this->now(),'updated_by'=>(int)$u->id]);return$this->response->setJSON(['success'=>true,'message'=>$l.' deleted successfully.']);}
}
