<?php
declare(strict_types=1);
namespace App\Controllers\Api;
use App\Models\ProjectMilestoneModel;
use CodeIgniter\HTTP\ResponseInterface;
class ProjectMilestonesController extends LabourApiController
{
 private ProjectMilestoneModel $model; public function __construct(){parent::__construct();$this->model=new ProjectMilestoneModel();}
 public function index():ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$b=$this->base()->where('m.company_id',$this->companyId($u));$pid=(int)($this->request->getGet('project_id')??0);if($pid){if(!$this->project($pid,$u))return$this->notFound('Project not found.');$b->where('m.project_id',$pid);}elseif(!$this->authorization->isSuperAdmin($u)){$ids=$this->authorization->getAccessibleBranchIds($u);if(!$ids)return$this->ok('Project milestones retrieved.','milestones',[]);$b->groupStart()->whereIn('p.branch_id',$ids)->orWhere('p.branch_id',null)->groupEnd();}return$this->ok('Project milestones retrieved.','milestones',$b->orderBy('m.target_date')->get()->getResultArray());}
 public function show(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$r=$this->row($id,$u);return$r?$this->ok('Project milestone retrieved.','milestone',$r):$this->notFound('Project milestone not found.');}
 public function create():ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$in=$this->normalize($this->input()??[]);$e=$this->validateInput($in,$u);if($e)return$this->invalid($e);$d=$this->data($in);$d+=['company_id'=>$this->companyId($u),'status_id'=>1,'progress_percentage'=>0,'weightage_percentage'=>0,'billing_trigger'=>0,'billing_percentage'=>0,'created_by'=>(int)$u->id,'updated_by'=>(int)$u->id];if(!$this->model->insert($d))return$this->invalid($this->model->errors());return$this->ok('Project milestone created.','milestone',$this->row((int)$this->model->getInsertID(),$u),201);}
 public function update(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();$old=$this->row($id,$u);if(!$old)return$this->notFound('Project milestone not found.');$in=$this->normalize($this->input()??[]);$merged=array_merge($old,$in);$e=$this->validateInput($merged,$u,$id);if($e)return$this->invalid($e);$d=$this->data($in);$d['updated_by']=(int)$u->id;if(!$this->model->update($id,$d))return$this->invalid($this->model->errors());return$this->show($id);}
 public function delete(int$id):ResponseInterface{$u=$this->user();if(!$u)return$this->unauthorized();if(!$this->row($id,$u))return$this->notFound('Project milestone not found.');$this->model->delete($id);return$this->ok('Project milestone archived.','id',$id);}
 private function validateInput(array$in,object$u,int$ignore=0):array{$e=$this->required($in,['project_id','work_stage_id','milestone_code','milestone_name','target_date']);if(!$this->project((int)($in['project_id']??0),$u,true))$e['project_id']='Select an accessible project.';if(!$this->activeMaster('work_categories_work_stage_masters',(int)($in['work_stage_id']??$in['execution_stage_id']??0)))$e['work_stage_id']='Select a valid execution stage.';$q=db_connect()->table('project_milestones')->where(['company_id'=>$this->companyId($u),'project_id'=>(int)($in['project_id']??0),'milestone_code'=>$in['milestone_code']??''])->where('deleted_at',null);if($ignore)$q->where('id !=',$ignore);if($q->countAllResults())$e['milestone_code']='Milestone code already exists for this project.';return$e;}
 private function data(array$in):array{if(isset($in['execution_stage_id'])&&!isset($in['work_stage_id']))$in['work_stage_id']=$in['execution_stage_id'];return array_intersect_key($in,array_flip(['project_id','work_stage_id','milestone_code','milestone_name','target_date','actual_completion_date','progress_percentage','weightage_percentage','billing_trigger','billing_percentage','status_id','remarks']));}
 private function normalize(array$in):array{if(isset($in['target_project_id'])&&!isset($in['project_id']))$in['project_id']=$in['target_project_id'];if(isset($in['execution_stage_id'])&&!isset($in['work_stage_id']))$in['work_stage_id']=$in['execution_stage_id'];if(isset($in['execution_phase_id'])&&!isset($in['work_stage_id']))$in['work_stage_id']=$in['execution_phase_id'];return$in;}
 private function row(int$id,object$u):?array{$r=$this->base()->where('m.company_id',$this->companyId($u))->where('m.id',$id)->get()->getRowArray();return$r&&$this->project((int)$r['project_id'],$u)?$r:null;}
 private function base(){return db_connect()->table('project_milestones m')->select('m.*,p.project_code,p.project_name,ws.work_stage_code,ws.work_stage_name,st.status_code,st.status_name')->join('projects p','p.id=m.project_id AND p.company_id=m.company_id')->join('work_categories_work_stage_masters ws','ws.id=m.work_stage_id','left')->join('project_milestone_status_masters st','st.id=m.status_id','left')->where('m.deleted_at',null);}
}
