<?php
declare(strict_types=1);
namespace App\Controllers\Api;

class ProjectCostingController extends ExpenseApiController
{
    public function summary(int$projectId){return$this->safe(function()use($projectId){if(!$u=$this->user())return$this->missing();if(!$this->project($projectId,$u))return$this->missing('Project not found or inaccessible.');$site=$this->request->getGet('site_id')!==null?(int)$this->request->getGet('site_id'):null;return$this->ok('Project costing summary generated.','project_costing',$this->calculate($projectId,$this->company($u),$site));});}
    public function snapshots(){return$this->safe(function(){if(!$u=$this->user())return$this->missing();$b=db_connect()->table('project_cost_snapshots s')->select('s.*,l.snapshot_level_code,l.snapshot_level_name,p.project_name')->join('project_cost_snapshots_snapshot_level_masters l','l.id=s.snapshot_level_id')->join('projects p','p.id=s.project_id')->where('s.company_id',$this->company($u));if($this->request->getGet('project_id')!==null)$b->where('s.project_id',(int)$this->request->getGet('project_id'));if($this->request->getGet('site_id')!==null)$b->where('s.site_id',(int)$this->request->getGet('site_id'));return$this->ok('Cost snapshots retrieved.','project_cost_snapshots',$b->orderBy('s.id','DESC')->get()->getResultArray());});}
    public function generate(){return$this->safe(function(){if(!$u=$this->user())return$this->missing();$d=$this->input();$e=$this->required($d,['project_id','snapshot_date']);if($e)return$this->invalid($e);$project=(int)$d['project_id'];$c=$this->company($u);if(!$this->project($project,$u,true))return$this->missing('Project not found or inaccessible.');$site=isset($d['site_id'])?(int)$d['site_id']:null;if(!$this->validSite($site,$project,$c))return$this->invalid(['site_id'=>'Site does not belong to the project.']);$cost=$this->calculate($project,$c,$site);$level=$this->masterId('project_cost_snapshots_snapshot_level_masters','snapshot_level_code',$site?'SITE':'PROJECT');$row=['company_id'=>$c,'project_id'=>$project,'site_id'=>$site,'snapshot_date'=>$d['snapshot_date'],'snapshot_level_id'=>$level,'approved_budget'=>$cost['approved_budget'],'revised_budget'=>$cost['revised_budget'],'material_commitment'=>$cost['material_commitment'],'subcontract_commitment'=>$cost['subcontract_commitment'],'expense_commitment'=>$cost['expense_commitment'],'material_actual'=>$cost['material_actual'],'labour_actual'=>$cost['labour_actual'],'subcontract_actual'=>$cost['subcontract_actual'],'site_expense_actual'=>$cost['site_expense_actual'],'total_actual_cost'=>$cost['total_actual_cost'],'total_paid'=>$cost['total_paid'],'total_outstanding'=>$cost['total_outstanding'],'forecast_cost_at_completion'=>$cost['forecast_cost_at_completion'],'budget_variance'=>$cost['budget_variance'],'cost_consumed_percent'=>$cost['cost_consumed_percent'],'data_upto'=>$this->now(),'generated_by'=>(int)$u->id,'generated_at'=>$this->now()];$db=db_connect();$db->table('project_cost_snapshots')->insert($row);$id=(int)$db->insertID();return$this->ok('Project cost snapshot generated.','project_cost_snapshot',$db->table('project_cost_snapshots')->where('id',$id)->get()->getRowArray(),201);});}
    private function calculate(int$p,int$c,?int$s):array{$db=db_connect();$sum=function(string$table,string$column,array$where,string$statusTable='',string$statusCode='')use($db,$s){$b=$db->table($table.' x')->selectSum('x.'.$column,'total')->where($where);if($s!==null&&$db->fieldExists('site_id',$table))$b->where('x.site_id',$s);if($statusTable){$b->join($statusTable.' st','st.id=x.status_id')->where('st.status_code',$statusCode);}if($db->fieldExists('deleted_at',$table))$b->where('x.deleted_at',null);return(float)($b->get()->getRowArray()['total']??0);};$budget=$sum('project_budgets','total_budget',['x.company_id'=>$c,'x.project_id'=>$p],'project_budgets_status_masters','APPROVED');$expenseCommit=$sum('expense_requests','estimated_amount',['x.company_id'=>$c,'x.project_id'=>$p],'expense_requests_status_masters','APPROVED');$expenseActual=$sum('expense_bills','net_payable',['x.company_id'=>$c,'x.project_id'=>$p],'expense_bills_status_masters','POSTED');$expensePaid=$sum('expense_bills','paid_amount',['x.company_id'=>$c,'x.project_id'=>$p],'expense_bills_status_masters','POSTED');$subCommit=$sum('subcontract_work_orders','revised_order_value',['x.company_id'=>$c,'x.project_id'=>$p],'subcontract_work_orders_status_masters','ACTIVE');$subActual=$sum('subcontract_ra_bills','net_certified_amount',['x.company_id'=>$c,'x.project_id'=>$p],'subcontract_ra_bills_status_masters','CERTIFIED');$subPaid=$sum('subcontract_payments','amount',['x.company_id'=>$c,'x.project_id'=>$p],'subcontract_payments_status_masters','PAID');$materialCommit=0.0;$materialActual=0.0;$labourActual=$sum('labour_wage_periods','net_payable',['x.company_id'=>$c,'x.project_id'=>$p],'labour_wage_periods_status_masters','APPROVED');$actual=$materialActual+$labourActual+$subActual+$expenseActual;$paid=$expensePaid+$subPaid;$out=max(0,$actual-$paid);$forecast=max($budget,$actual+$materialCommit+$subCommit+$expenseCommit);return['approved_budget'=>$budget,'revised_budget'=>$budget,'material_commitment'=>$materialCommit,'subcontract_commitment'=>$subCommit,'expense_commitment'=>$expenseCommit,'material_actual'=>$materialActual,'labour_actual'=>$labourActual,'subcontract_actual'=>$subActual,'site_expense_actual'=>$expenseActual,'total_actual_cost'=>$actual,'total_paid'=>$paid,'total_outstanding'=>$out,'forecast_cost_at_completion'=>$forecast,'budget_variance'=>$budget-$forecast,'cost_consumed_percent'=>$budget>0?round($actual/$budget*100,4):0];}
}
